### ISSUE TITLE
R2C notinplace modifies input

### ISSUE THREAD

**Issue by antholzer** [ROCmSoftwarePlatform/rocFFT#268]
### What is the expected behavior
-  A plan with `rocfft_placement_notinplace` should not change the input buffer.

### What actually happens
-  For real to complex (single and double) this does not seem to be the case i.e. using
```
rocfft_plan_create(&plan, rocfft_placement_notinplace, rocfft_transform_type_real_forward, ...);

rocfft_execute(plan, (void**) &x, (void **) &y, NULL);
```
changes `x`.

### How to reproduce
-  Using [this example](https://gist.github.com/antholzer/d746dc946261400f2612015e6337325b) gives:
```
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
```
but they should be the same.

### Environment
| Hardware | description |
|-----|-----|
| GPU | gfx803 |
| CPU | Threadripper 1950X |

| Software | version |
|-----|-----|
| ROCK | v2.9 |
| ROCR | v1.1 |
| HCC | v2.9 |
| Library | v0.9.7 |

Used the rocm docker image with kernel v5.3.7.

**Comment by malcolmroberts** [comment]
The real/complex transforms, for reasons of algorithmic efficiency, may change the input buffers.  I believe that this is new behaviour which is due to an important improvement in the underlying algorithm.  We are working on improving the documentation; sorry that this wasn't clear.

For the sake of comparison, see http://fftw.org/fftw3_doc/One_002dDimensional-DFTs-of-Real-Data.html#One_002dDimensional-DFTs-of-Real-Data
