### ISSUE TITLE
Incorrect result with even length C2R inverse transform

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCmSoftwarePlatform/rocFFT#284]
1D complex inverse FFT with length 8
Input: [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
Expected output: [ 0.         -1.20710678  0.5        -0.20710678  0.          0.20710678
 -0.5         1.20710678]
Observed output: [ 0.5        -0.7071068   1.          0.29289317  0.5         0.7071068  0.          1.7071068 ]

Happens both with 3.0 release and with the current develop branch. 
Only happens with even length and only when the last element of the input has nonzero imaginary part.

**Comment by malcolmroberts** [comment]
So, this is a complex-to-real transform?  What do you mean by half-length?

**Comment by ekuznetsov139** [comment]
just that input length is half of output length.
`>>> v=np.array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j],dtype=np.complex64)
>>> np.fft.irfft(v,8)
array([ 0.        , -1.20710678,  0.5       , -0.20710678,  0.        ,
        0.20710678, -0.5       ,  1.20710678])
`

**Comment by malcolmroberts** [comment]
If the length is divisible by 2, then the first and last element must be purely real-valued.  This is due to Hermitian symmetry of the output of a real-to-complex Fourier transform.  We assume that this value is zero; having a non-zero value will produce incorrect results, but this is an data formatting error, and not a transform error.
