### ISSUE TITLE
Not-in-place real-to-complex 2D forward FFT modifies the input

### ISSUE THREAD

**Issue by lashgar** [ROCmSoftwarePlatform/rocFFT#298]
### What is the expected behavior
Not-in-place real-to-complex 2D forward FFT should not modify the input.

### What actually happens
Input is modified after rocfft_execution completes. There is a pattern in the data that could be a clue to rocFFT developers on what has gone wrong.

### How to reproduce
I could reproduce in two ways:
1) In standard rocfft sample at docs/samples/real2complex_2d.cpp, dump and compare input after forward rocfft_execution completes.
2) Use the sample code I provided ([failure_repro.cpp.txt](https://github.com/ROCmSoftwarePlatform/rocFFT/files/4731237/failure_repro.cpp.txt)).

### Environment
CPU => Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
GPU => gfx900

| Software | version |
Ubuntu 18.04
HIP version: 3.3.20126-2dbba46b
clang version 11.0.0
rocm 3.3.0 => standard RPM
rocfft => latest built from source (revision 419222798922a9cc303fb28ef3a8b8196124f139 May 28)
rocFFT compiled using HIP_PLATFORM=clang

**Comment by malcolmroberts** [comment]
The real/complex algorithms require that they overwrite the work buffer; we would have to create an entirely separate work buffer in order to avoid this, which would be massively inefficient.

Moreover, other implementations (eg FFTW: http://www.fftw.org/fftw3_doc/One_002dDimensional-DFTs-of-Real-Data.html) overwrite input data as well.

**Comment by dmcdougall** [comment]
@lashgar I totally understand why you might think that.  The property of 'in-place' versus not 'in-place' simply determines whether or not the _result_ is placed in the input array.  Of course, in-place transforms therefore _must_ modify the input array, because that's where they put the result.  Transforms that are 'not in-place' don't put the result in the input array, but that doesn't necessarily mean that they can't put other things in the input array, like intermediate answers or other temporary computations.

As @malmcolmroberts pointed out, FFTW behaves the same way.  We tried to design rocfft to echo some of the semantics of FFTW so that folks using either felt comfortable.

If you need to ensure that the input array is unmodified, as is common in a lot of pseudo-spectral codes, then make a copy before calling rocfft.

**Comment by lashgar** [comment]
Thanks @malcolmroberts & @dmcdougall for clarification. I will wrap my FFT exec calls to buffer the input.
