### ISSUE TITLE
cstddef not found

### ISSUE THREAD

**Issue by yuxianglin** [ROCmSoftwarePlatform/rocFFT#306]
### What is the expected behavior
-  
Hi, I am trying to replace the clfft to the rocm fft lib but my original code is written by c (not cpp), after gcc compiling, I got the error cstddef not found in header file, I wonder is there a circumvent this?
### What actually happens
-  

### How to reproduce
-  

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

**Comment by evetsso** [comment]
rocFFT requires a C++ compiler.

If you use g++ instead of gcc, things should build successfully.

If for some reason it's difficult to change the compiler name, you could work around it by adding `-x c++` at compile time and `-lstdc++` at link time to try to convince gcc to build and link like g++ would.
