### ISSUE TITLE
Can't find valid buffer assignment with current buffers

### ISSUE THREAD

**Issue by zjin-lcf** [ROCmSoftwarePlatform/rocFFT#343]
I am not familiar with FFT. After porting the cuda codes with Hipify, I observed the errors. Could you please comment on the differences between cuFFT and rocFFT ?

To reproduce:
1 git clone https://github.com/zjin-lcf/distributed-gpu.git
2 cd distributed-gpu/multi-gpu
3 hipify the cuda codes
4. change the Makefile to build with hipcc and hipfft
5. run the program
   ./packed_fft.x 32       
   ./fused_packed.x 32     

Thanks

**Comment by evetsso** [comment]
This `Can't find valid buffer assignment with current buffers` error was introduced in ROCm 4.5 and will be fixed in the next release after 4.5.x by 11c4a2cb23b3b910a8dfb6856d89764a94c8e185.

The message can be ignored because it's complaining about FFT plans that never got executed.  When a hipFFT plan is created, we need to create multiple rocFFT plans because we don't know the placement and direction that will actually be needed.  For some plans, in-place execution is impossible and the message is complaining about that.  But so long as the executed transform is not in-place, there's no actual problem.

**Comment by zjin-lcf** [comment]
Can you reopen the issue ?
The changes just print the error message somewhere else; it does not solve the problem at all.
The question is what need to be modified in the hipified codes for fixing the error ?

**Comment by evetsso** [comment]
Nothing needs to be modified in the hipified code.  The error is encountered internally within hipFFT because the supplied parameters are not valid for an in-place transform.  The bug was that the error is internal and should not have been printed or exposed outside of hipFFT, which is what the mentioned commit fixes.

**Comment by zjin-lcf** [comment]
Sorry, I probably misunderstood your reply and fix. Since the hipified codes will not need to be modified, I will check the outputs of the cuFFT results with those of the hipFFT results.

Thanks.
