### ISSUE TITLE
Is there some example cases for calling CS_KERNEL_STOCKHAM_BLOCK_CR?

### ISSUE THREAD

**Issue by xiuyangleiasp** [ROCmSoftwarePlatform/rocFFT#367]
Hi, When I try to understand the schemes of rocFFT,  I couldn't give a 1d c2c case to call CS_KERNEL_STOCKHAM_BLOCK_CR.
So Is there some cases for calling it?
thanks.

**Comment by evetsso** [comment]
Hi @xiuyangleiasp,

This kernel is only used sparingly in rocFFT because it hasn't proven to be a win in more general usage.

The logic is in `Apply_SBCR` in library/src/node_factory.cpp.  It's only enabled for 3D transforms on MI100 and MI200 at the moment, and only certain problem sizes are generated with `sbcr_kernels` in library/src/device/kernel-generator.py.

But if you are on either of those architectures, you can see this kernel running with `rocfft-test --length 56 56 56 -o`.

I believe that answers your question, so I will close this issue.
