### ISSUE TITLE
Plan creation kills performance

### ISSUE THREAD

**Issue by lpetrov00** [ROCmSoftwarePlatform/rocFFT#390]
Dear developers,

  I would like you to thank for you work on rocfft. I am trying 
to evaluate whether rocfft can replace FFTW for my needs, but
I still have difficulties.

Issue #1:

  In my use case I need perform large 2D FFT of variable dimensions.
The number of combination of dimensions is in the order of 100-1000.
With FFTW I run a program that computes so-called wisdom-file for 
all combinations of dimensions. This is a lengthy process, but
a user has to run it only once. I did not find that feature in rocfft.
Documentation tells something vaguely about ROCFFT_RTC_CACHE_PATH.
I set it to a writable file /tmp/p.p, run rocfft -- nothing was 
written. I called rocfft_plan_get_print after creation of the plan --
nothing was written in stdout.

  I ran a timing test for a computation in place of a 2D FFT of several dimensions. Fist value is time of sending data from RAM to device
(AMD PRO VII) in seconds, 2nd is plan creation time, 3d is computation of 
FFT, the 4th is sending data back from the device to RAM. For 
comparison, the last column istiming of FFTW using 16 cores of
3990X:

 4000x4000    0.005  0.719  0.002  0.008 total:   0.725  || 0.042
 4096x4096    0.005  0.602  0.002  0.006 Total:   0.623  || 0.032
 8192x8192    0.019  0.516  0.009  0.021 Total:   0.567  || 0.064
16384x16384   0.075  0.513  0.041  0.077 Total:   0.708  || 0.368
32000x32000   0.284  0.002  0.541  0.418 Total:   1.245  || 2.460

The table shows wall time on the idle computer.

  You see, time for plan creation is the show killer. My question is
how to  save and reuse plan without its very expensive creation 
in a similar what as it is implemented with FFTW?

Issue #2:

 I found that rocfft cannot preform in-place transforms with 
an array size more than 1/2 of the device memory. I found vague 
mentioning of buffers in documentation. Looks like rocfft grabs a 
temporary buffer with a size of the array to be transformed.
Is there a way to overcome this serious limitation?

Tested rocfft version: 5.4.1
Version of rocm and hip libraries: 5.4.1
OS: Linux, kernel 6.1.1
Card series:          Vega 20
Card model:           0x081e
Card SKU:             D16406
CPU:                  3990X

**Comment by evetsso** [comment]
Hi @lpetrov00, thanks for the bug report.

For your first issue, it looks like rocFFT from ROCm 5.4.1 won't need to runtime-compile any kernels.  That will change in ROCm 5.5, it would be a good idea for you to keep setting ROCFFT_RTC_CACHE_PATH in the environment to avoid unnecessary recompilation.

As for the expense of the rest of plan creation, the typical advice here would be to have you hold on to the plan handles for longer - after creating a plan, you can execute it many times before destroying it, which helps you amortize the plan creation time across many executions.  Are you able to arrange your usage this way?

We are looking reducing that cost by remembering the resulting plan details between calls to `rocfft_plan_create`, but we probably won't have anything to substantially help this usage pattern for the next couple of releases at least.

For your second issue, rocFFT currently uses temporary buffers for these transforms because we transpose the data in the middle of the FFT.  Transpose operations generally require separate input and output buffers.  It's unlikely this situation will improve in the foreseeable future - while we can potentially get rid of some of the explicit transpose kernels in the plan (CS_KERNEL_TRANSPOSE), other kernels like CS_KERNEL_STOCKHAM_BLOCK_RC will still need to do their own transposing of data.

**Comment by lpetrov00** [comment]
Dear Steve,

  Thank you for a response. I already tested reusing plans during
run-time and it works. I checked, I have 780 second  combinations
of 2D transform dimensions. If I try to create all plans on startup, 
considering that plan creation takes 0.5 sec per dimension 
combination, it would take over 5 minutes on start up. That is why 
I am thinking how to create a plan once, dump it, and then read 
that dump on startup. I did not put my fingers into the source code
yet, but I guess a plan is a pointer to a data structure. If one 
would write down the contents of that data structure to a file, 
stop the executable, start the executable again, read the contents 
of that data structure into memory, and pass the data structure 
pointer to rocfft_execute, will it work? Or there are some 
obstacles that would prevent it?

  Concerning the second issue, I understand that some overheads
are inevitable, but if amount of temporary memory will be reduced 
in the future that would enhance the use case of rockfft.

Leonid

**Comment by evetsso** [comment]
One workaround would be to create plans in parallel.  So long as you set the HIP device in each thread (if you have multiple devices present), you should be able to get a large speedup that way.  Your CPU has 128 threads - can you test with that and see what improvement you get?

Adding some way to serialize and deserialize plan structures is plausible but would need a bunch of design work.  We will consider that improvement in a future rocFFT release, though it's possible that we might get enough of a benefit from the cost reduction work I mentioned earlier, to make a separate API unnecessary.

**Comment by evetsso** [comment]
I'm closing this issue, as I believe creating plans in parallel is the best way forward for the time being.  Please comment and/or reopen if this is not sufficient.
