### ISSUE TITLE
Selecting gpu to run rocfft

### ISSUE THREAD

**Issue by fftfp64** [ROCmSoftwarePlatform/rocFFT#397]
**rocm-5.4.1**

In opencl one uses context and queue to select gpu when more than one are available.
It is not clear (to a beginner at least) how to select the target gpu (out of 4 available) with rocfft.
How does one do this in C?

**Comment by evetsso** [comment]
Hi @fftfp64, rocFFT is implemented in terms of HIP, so you would need to use HIP API calls to select the current device before creating and executing the FFT plan.  [As per the HIP API documentation](https://docs.amd.com/bundle/HIP-API-Guide-v5.4/page/a00180.html), you would use `hipSetDevice` to pick the device you want.

When a rocFFT plan is created using `rocfft_plan_create`, it is created for the current device as chosen by `hipSetDevice`, or device 0 if no device is explicitly chosen.  The current device must be the same device when `rocfft_plan_execute` is called to actually perform the work of the FFT.

This is not currently explicit in the rocFFT documentation.  I've noted this deficiency and will work to get this addressed in the near future.

Since I believe this response answers your question, I'm closing this issue.  Please feel free to add comments or reopen it if you have additional questions on this topic.  Thanks!

**Comment by fftfp64** [comment]
This is clear enough; thank you very much. The rocfft is meant to replace the cflfft i've been using.

For those who may come to this query via web search, i will add that i had to add  the following option to the load statement  (the appropriate headers and lib paths are assumed):  -lamdhip64

++

**Comment by fftfp64** [comment]
Hello,
mixing ocl and hip is a bit of a problem.

is there a safe way of passing data created as cl_men (and contains double)  to 
rocfft_execute(plan, here, NULL, NULL)? must avoid copying.

**Comment by evetsso** [comment]
Sorry, I don't believe there's an easy way to do this - OpenCL and HIP have different ways of looking at the GPU memory and they don't sound very compatible.

I have no idea how well this would work, but you could attempt an EnqueueMapBuffer on the OpenCL side to get a buffer mapped to host address space.  hipHostRegister could then try to make that buffer usable in HIP.

It's entirely possible that (assuming this even works) this will perform far worse than just copying the data to and from the host.
